In [1]:
import polars as pl

In [2]:
pl.Config.set_tbl_cols(-1)  # Display all columns
pl.Config.set_tbl_rows(-1)  # Display all rows

polars.config.Config

In [3]:
#script to create a metada file for wagtail run
#inside the metadata file, we will have the following columns:
#1. sample_id
#2. total input reads (from qc reports)
#3. total retained reads (from qc reports)
#4. total retained reads percentage (#3/#2*100)
#5-18. deblur stats result
#19. total reads for mapping (from samtools flagstat reports line 1)
#20. total all mapped reads with percentage (from samtools flagstat reports line 7)
#21. total all primary mapped reads with percentage (from samtools flagstat reports line 8)

#1-18 is combining from the qc-stats report with deblur stats result
#19-21 is from samtools flagstat report and take only line 1, 7, and 8

In [5]:
#read the qc-stats report and deblur stats result
qc_stats = pl.read_csv("qc-stats.csv")
deblur_stats = pl.read_csv("deblur-stats.csv")

In [11]:
qc_stats[:4]

shape: (1, 6)
┌───────────┬─────────────────┬─────────────────┬────────────────┬────────────────┬────────────────┐
│ sample-id ┆ total-input-rea ┆ total-retained- ┆ reads-truncate ┆ reads-too-shor ┆ reads-exceedin │
│ ---       ┆ ds              ┆ reads           ┆ d              ┆ t-after-trunca ┆ g-maximum-ambi │
│ str       ┆ ---             ┆ ---             ┆ ---            ┆ tion           ┆ guou…          │
│           ┆ i64             ┆ i64             ┆ i64            ┆ ---            ┆ ---            │
│           ┆                 ┆                 ┆                ┆ i64            ┆ i64            │
╞═══════════╪═════════════════╪═════════════════╪════════════════╪════════════════╪════════════════╡
│ V1V2      ┆ 73176           ┆ 73031           ┆ 104            ┆ 104            ┆ 41             │
└───────────┴─────────────────┴─────────────────┴────────────────┴────────────────┴────────────────┘

In [12]:
#add percentage of total retained reads to the qc_stats dataframe
#calculate the total retained reads/total input reads * 100 and save it to a new column called retained-reads-percentage
qc_stats1 = qc_stats.with_columns((pl.col("total-retained-reads") / pl.col("total-input-reads") * 100).alias("retained-reads-percentage"))
qc_stats1[:4]

shape: (1, 7)
┌───────────┬──────────────┬──────────────┬──────────────┬─────────────┬─────────────┬─────────────┐
│ sample-id ┆ total-input- ┆ total-retain ┆ reads-trunca ┆ reads-too-s ┆ reads-excee ┆ retained-re │
│ ---       ┆ reads        ┆ ed-reads     ┆ ted          ┆ hort-after- ┆ ding-maximu ┆ ads-percent │
│ str       ┆ ---          ┆ ---          ┆ ---          ┆ truncation  ┆ m-ambiguou… ┆ age         │
│           ┆ i64          ┆ i64          ┆ i64          ┆ ---         ┆ ---         ┆ ---         │
│           ┆              ┆              ┆              ┆ i64         ┆ i64         ┆ f64         │
╞═══════════╪══════════════╪══════════════╪══════════════╪═════════════╪═════════════╪═════════════╡
│ V1V2      ┆ 73176        ┆ 73031        ┆ 104          ┆ 104         ┆ 41          ┆ 99.801848   │
└───────────┴──────────────┴──────────────┴──────────────┴─────────────┴─────────────┴─────────────┘

In [7]:
deblur_stats[:4]

shape: (1, 14)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┬───────┬───────┬───────┬───────┬───────┬───────┐
│ sam ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ reads- ┆ uniqu ┆ reads ┆ uniqu ┆ reads ┆ uniqu ┆ reads │
│ ple ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ hit-ar ┆ e-rea ┆ -chim ┆ e-rea ┆ -hit- ┆ e-rea ┆ -miss │
│ -id ┆ raw ┆ -re ┆ der ┆ -re ┆ deb ┆ -re ┆ tifact ┆ ds-ch ┆ eric  ┆ ds-hi ┆ refer ┆ ds-mi ┆ ed-re │
│ --- ┆ --- ┆ ads ┆ ep  ┆ ads ┆ lur ┆ ads ┆ ---    ┆ imeri ┆ ---   ┆ t-ref ┆ ence  ┆ ssed- ┆ feren │
│ str ┆ i64 ┆ -de ┆ --- ┆ -de ┆ --- ┆ -hi ┆ i64    ┆ c     ┆ i64   ┆ erenc ┆ ---   ┆ refer ┆ ce    │
│     ┆     ┆ rep ┆ i64 ┆ blu ┆ i64 ┆ t-a ┆        ┆ ---   ┆       ┆ e     ┆ i64   ┆ ence  ┆ ---   │
│     ┆     ┆ --- ┆     ┆ r   ┆     ┆ rti ┆        ┆ i64   ┆       ┆ ---   ┆       ┆ ---   ┆ i64   │
│     ┆     ┆ i64 ┆     ┆ --- ┆     ┆ fac ┆        ┆       ┆       ┆ i64   ┆       ┆ i64   ┆       │
│     ┆     ┆     ┆     ┆ i64 ┆     ┆ t   ┆        ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆        ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆        ┆       ┆       ┆       ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╡
│ V1V ┆ 730 ┆ 299 ┆ 512 ┆ 174 ┆ 136 ┆ 0   ┆ 0      ┆ 31    ┆ 607   ┆ 143   ┆ 13076 ┆ 0     ┆ 0     │
│ 2   ┆ 31  ┆ 2   ┆ 64  ┆     ┆ 83  ┆     ┆        ┆       ┆       ┆       ┆       ┆       ┆       │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴────────┴───────┴───────┴───────┴───────┴───────┴───────┘

In [13]:
#combine the qc_stats1 and deblur_stats dataframe
#we will use the sample-id column to join the two dataframes
metadata = qc_stats1.join(deblur_stats, on="sample-id")
metadata[:4]

shape: (1, 20)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ tot ┆ tot ┆ rea ┆ rea ┆ rea ┆ ret ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea │
│ ple ┆ al- ┆ al- ┆ ds- ┆ ds- ┆ ds- ┆ ain ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- │
│ -id ┆ inp ┆ ret ┆ tru ┆ too ┆ exc ┆ ed- ┆ raw ┆ -re ┆ der ┆ -re ┆ deb ┆ -re ┆ hit ┆ -re ┆ chi ┆ -re ┆ hit ┆ -re ┆ mis │
│ --- ┆ ut- ┆ ain ┆ nca ┆ -sh ┆ eed ┆ rea ┆ --- ┆ ads ┆ ep  ┆ ads ┆ lur ┆ ads ┆ -ar ┆ ads ┆ mer ┆ ads ┆ -re ┆ ads ┆ sed │
│ str ┆ rea ┆ ed- ┆ ted ┆ ort ┆ ing ┆ ds- ┆ i64 ┆ -de ┆ --- ┆ -de ┆ --- ┆ -hi ┆ tif ┆ -ch ┆ ic  ┆ -hi ┆ fer ┆ -mi ┆ -re │
│     ┆ ds  ┆ rea ┆ --- ┆ -af ┆ -ma ┆ per ┆     ┆ rep ┆ i64 ┆ blu ┆ i64 ┆ t-a ┆ act ┆ ime ┆ --- ┆ t-r ┆ enc ┆ sse ┆ fer │
│     ┆ --- ┆ ds  ┆ i64 ┆ ter ┆ xim ┆ cen ┆     ┆ --- ┆     ┆ r   ┆     ┆ rti ┆ --- ┆ ric ┆ i64 ┆ efe ┆ e   ┆ d-r ┆ enc │
│     ┆ i64 ┆ --- ┆     ┆ -tr ┆ um- ┆ tag ┆     ┆ i64 ┆     ┆ --- ┆     ┆ fac ┆ i64 ┆ --- ┆     ┆ ren ┆ --- ┆ efe ┆ e   │
│     ┆     ┆ i64 ┆     ┆ unc ┆ amb ┆ e   ┆     ┆     ┆     ┆ i64 ┆     ┆ t   ┆     ┆ i64 ┆     ┆ ce  ┆ i64 ┆ ren ┆ --- │
│     ┆     ┆     ┆     ┆ ati ┆ igu ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆     ┆ ce  ┆ i64 │
│     ┆     ┆     ┆     ┆ on  ┆ ou… ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆ i64 ┆     ┆ --- ┆     │
│     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     │
│     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ V1V ┆ 731 ┆ 730 ┆ 104 ┆ 104 ┆ 41  ┆ 99. ┆ 730 ┆ 299 ┆ 512 ┆ 174 ┆ 136 ┆ 0   ┆ 0   ┆ 31  ┆ 607 ┆ 143 ┆ 130 ┆ 0   ┆ 0   │
│ 2   ┆ 76  ┆ 31  ┆     ┆     ┆     ┆ 801 ┆ 31  ┆ 2   ┆ 64  ┆     ┆ 83  ┆     ┆     ┆     ┆     ┆     ┆ 76  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ 848 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [53]:
#read the samtools flagstat report
samtools_flagstat = pl.read_csv("V1V2_flagstat_tsv.txt", separator= '\t', has_header=False)
samtools_flagstat[:10]
index = [0, 1, 2, 3, 7, 8, 9]

In [54]:
samtools_flagstat1 = samtools_flagstat.filter(pl.Series(range(len(samtools_flagstat))).is_in(index))
print(samtools_flagstat1)

shape: (7, 3)
┌──────────┬──────────┬───────────────────────────────────┐
│ column_1 ┆ column_2 ┆ column_3                          │
│ ---      ┆ ---      ┆ ---                               │
│ str      ┆ str      ┆ str                               │
╞══════════╪══════════╪═══════════════════════════════════╡
│ 164      ┆ 0        ┆ total (QC-passed reads + QC-fail… │
│ 143      ┆ 0        ┆ primary                           │
│ 0        ┆ 0        ┆ secondary                         │
│ 21       ┆ 0        ┆ supplementary                     │
│ 100.00%  ┆ N/A      ┆ mapped %                          │
│ 143      ┆ 0        ┆ primary mapped                    │
│ 100.00%  ┆ N/A      ┆ primary mapped %                  │
└──────────┴──────────┴───────────────────────────────────┘

In [55]:
#transpose the samtools_flagstat dataframe and use the column_3 content as the column name
samtools_flagstat2 = samtools_flagstat1.select([pl.col("column_1"), pl.col("column_2")]).transpose()
samtools_flagstat2.columns = samtools_flagstat1["column_3"].to_list()
samtools_flagstat2[:4]

shape: (2, 7)
┌────────────┬─────────┬───────────┬───────────────┬──────────┬──────────────────┬─────────────────┐
│ total      ┆ primary ┆ secondary ┆ supplementary ┆ mapped % ┆ primary mapped   ┆ primary mapped  │
│ (QC-passed ┆ ---     ┆ ---       ┆ ---           ┆ ---      ┆ ---              ┆ %               │
│ reads +    ┆ str     ┆ str       ┆ str           ┆ str      ┆ str              ┆ ---             │
│ QC-fail…   ┆         ┆           ┆               ┆          ┆                  ┆ str             │
│ ---        ┆         ┆           ┆               ┆          ┆                  ┆                 │
│ str        ┆         ┆           ┆               ┆          ┆                  ┆                 │
╞════════════╪═════════╪═══════════╪═══════════════╪══════════╪══════════════════╪═════════════════╡
│ 164        ┆ 143     ┆ 0         ┆ 21            ┆ 100.00%  ┆ 143              ┆ 100.00%         │
│ 0          ┆ 0       ┆ 0         ┆ 0             ┆ N/A      ┆ 0                ┆ N/A             │
└────────────┴─────────┴───────────┴───────────────┴──────────┴──────────────────┴─────────────────┘

In [57]:
#delete row 2 of samtools_flagstat1
row_to_delete = [1]
samtools_flagstat3 = samtools_flagstat2.filter(~pl.Series(range(len(samtools_flagstat2))).is_in(row_to_delete))
samtools_flagstat3[:4]

shape: (1, 7)
┌────────────┬─────────┬───────────┬───────────────┬──────────┬──────────────────┬─────────────────┐
│ total      ┆ primary ┆ secondary ┆ supplementary ┆ mapped % ┆ primary mapped   ┆ primary mapped  │
│ (QC-passed ┆ ---     ┆ ---       ┆ ---           ┆ ---      ┆ ---              ┆ %               │
│ reads +    ┆ str     ┆ str       ┆ str           ┆ str      ┆ str              ┆ ---             │
│ QC-fail…   ┆         ┆           ┆               ┆          ┆                  ┆ str             │
│ ---        ┆         ┆           ┆               ┆          ┆                  ┆                 │
│ str        ┆         ┆           ┆               ┆          ┆                  ┆                 │
╞════════════╪═════════╪═══════════╪═══════════════╪══════════╪══════════════════╪═════════════════╡
│ 164        ┆ 143     ┆ 0         ┆ 21            ┆ 100.00%  ┆ 143              ┆ 100.00%         │
└────────────┴─────────┴───────────┴───────────────┴──────────┴──────────────────┴─────────────────┘

In [58]:
#add one more column with the column name as sample-id and the value is the same as the sample-id in the metadata dataframe
samtools_flagstat4 = samtools_flagstat3.with_columns(metadata["sample-id"])
samtools_flagstat4[:4]

shape: (1, 8)
┌────────────┬─────────┬───────────┬───────────────┬──────────┬─────────┬──────────┬───────────┐
│ total      ┆ primary ┆ secondary ┆ supplementary ┆ mapped % ┆ primary ┆ primary  ┆ sample-id │
│ (QC-passed ┆ ---     ┆ ---       ┆ ---           ┆ ---      ┆ mapped  ┆ mapped % ┆ ---       │
│ reads +    ┆ str     ┆ str       ┆ str           ┆ str      ┆ ---     ┆ ---      ┆ str       │
│ QC-fail…   ┆         ┆           ┆               ┆          ┆ str     ┆ str      ┆           │
│ ---        ┆         ┆           ┆               ┆          ┆         ┆          ┆           │
│ str        ┆         ┆           ┆               ┆          ┆         ┆          ┆           │
╞════════════╪═════════╪═══════════╪═══════════════╪══════════╪═════════╪══════════╪═══════════╡
│ 164        ┆ 143     ┆ 0         ┆ 21            ┆ 100.00%  ┆ 143     ┆ 100.00%  ┆ V1V2      │
└────────────┴─────────┴───────────┴───────────────┴──────────┴─────────┴──────────┴───────────┘

In [59]:
#combine the metadata dataframe with the samtools_flagstat4 dataframe based on the sample-id column
metadata1 = metadata.join(samtools_flagstat4, on="sample-id")
metadata1[:4]

shape: (1, 27)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ tot ┆ tot ┆ rea ┆ rea ┆ rea ┆ ret ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ tot ┆ pri ┆ sec ┆ sup ┆ map ┆ pri ┆ pri │
│ ple ┆ al- ┆ al- ┆ ds- ┆ ds- ┆ ds- ┆ ain ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ al  ┆ mar ┆ ond ┆ ple ┆ ped ┆ mar ┆ mar │
│ -id ┆ inp ┆ ret ┆ tru ┆ too ┆ exc ┆ ed- ┆ raw ┆ -re ┆ der ┆ -re ┆ deb ┆ -re ┆ hit ┆ -re ┆ chi ┆ -re ┆ hit ┆ -re ┆ mis ┆ (QC ┆ y   ┆ ary ┆ men ┆ %   ┆ y   ┆ y   │
│ --- ┆ ut- ┆ ain ┆ nca ┆ -sh ┆ eed ┆ rea ┆ --- ┆ ads ┆ ep  ┆ ads ┆ lur ┆ ads ┆ -ar ┆ ads ┆ mer ┆ ads ┆ -re ┆ ads ┆ sed ┆ -pa ┆ --- ┆ --- ┆ tar ┆ --- ┆ map ┆ map │
│ str ┆ rea ┆ ed- ┆ ted ┆ ort ┆ ing ┆ ds- ┆ i64 ┆ -de ┆ --- ┆ -de ┆ --- ┆ -hi ┆ tif ┆ -ch ┆ ic  ┆ -hi ┆ fer ┆ -mi ┆ -re ┆ sse ┆ str ┆ str ┆ y   ┆ str ┆ ped ┆ ped │
│     ┆ ds  ┆ rea ┆ --- ┆ -af ┆ -ma ┆ per ┆     ┆ rep ┆ i64 ┆ blu ┆ i64 ┆ t-a ┆ act ┆ ime ┆ --- ┆ t-r ┆ enc ┆ sse ┆ fer ┆ d   ┆     ┆     ┆ --- ┆     ┆ --- ┆ %   │
│     ┆ --- ┆ ds  ┆ i64 ┆ ter ┆ xim ┆ cen ┆     ┆ --- ┆     ┆ r   ┆     ┆ rti ┆ --- ┆ ric ┆ i64 ┆ efe ┆ e   ┆ d-r ┆ enc ┆ rea ┆     ┆     ┆ str ┆     ┆ str ┆ --- │
│     ┆ i64 ┆ --- ┆     ┆ -tr ┆ um- ┆ tag ┆     ┆ i64 ┆     ┆ --- ┆     ┆ fac ┆ i64 ┆ --- ┆     ┆ ren ┆ --- ┆ efe ┆ e   ┆ ds  ┆     ┆     ┆     ┆     ┆     ┆ str │
│     ┆     ┆ i64 ┆     ┆ unc ┆ amb ┆ e   ┆     ┆     ┆     ┆ i64 ┆     ┆ t   ┆     ┆ i64 ┆     ┆ ce  ┆ i64 ┆ ren ┆ --- ┆ +   ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ ati ┆ igu ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆     ┆ ce  ┆ i64 ┆ QC- ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ on  ┆ ou… ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆ i64 ┆     ┆ --- ┆     ┆ fai ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆ l…  ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ V1V ┆ 731 ┆ 730 ┆ 104 ┆ 104 ┆ 41  ┆ 99. ┆ 730 ┆ 299 ┆ 512 ┆ 174 ┆ 136 ┆ 0   ┆ 0   ┆ 31  ┆ 607 ┆ 143 ┆ 130 ┆ 0   ┆ 0   ┆ 164 ┆ 143 ┆ 0   ┆ 21  ┆ 100 ┆ 143 ┆ 100 │
│ 2   ┆ 76  ┆ 31  ┆     ┆     ┆     ┆ 801 ┆ 31  ┆ 2   ┆ 64  ┆     ┆ 83  ┆     ┆     ┆     ┆     ┆     ┆ 76  ┆     ┆     ┆     ┆     ┆     ┆     ┆ .00 ┆     ┆ .00 │
│     ┆     ┆     ┆     ┆     ┆     ┆ 848 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ %   ┆     ┆ %   │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [60]:
#read some file and then append the metadata1 dataframe to the file
metadata1.write_csv("metadata.tsv", separator="\t", has_header=True)

In [63]:
#testing to combine 2 metadata files into a single metadata file without duplicating all headers
metadata3 = pl.read_csv("metadata.tsv", separator="\t", has_header=True)
metadata2 = pl.read_csv("metadata2.tsv", separator="\t", has_header=True)
metadata2[:4]

shape: (1, 27)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ tot ┆ tot ┆ rea ┆ rea ┆ rea ┆ ret ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ tot ┆ pri ┆ sec ┆ sup ┆ map ┆ pri ┆ pri │
│ ple ┆ al- ┆ al- ┆ ds- ┆ ds- ┆ ds- ┆ ain ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ al  ┆ mar ┆ ond ┆ ple ┆ ped ┆ mar ┆ mar │
│ -id ┆ inp ┆ ret ┆ tru ┆ too ┆ exc ┆ ed- ┆ raw ┆ -re ┆ der ┆ -re ┆ deb ┆ -re ┆ hit ┆ -re ┆ chi ┆ -re ┆ hit ┆ -re ┆ mis ┆ (QC ┆ y   ┆ ary ┆ men ┆ %   ┆ y   ┆ y   │
│ --- ┆ ut- ┆ ain ┆ nca ┆ -sh ┆ eed ┆ rea ┆ --- ┆ ads ┆ ep  ┆ ads ┆ lur ┆ ads ┆ -ar ┆ ads ┆ mer ┆ ads ┆ -re ┆ ads ┆ sed ┆ -pa ┆ --- ┆ --- ┆ tar ┆ --- ┆ map ┆ map │
│ str ┆ rea ┆ ed- ┆ ted ┆ ort ┆ ing ┆ ds- ┆ i64 ┆ -de ┆ --- ┆ -de ┆ --- ┆ -hi ┆ tif ┆ -ch ┆ ic  ┆ -hi ┆ fer ┆ -mi ┆ -re ┆ sse ┆ i64 ┆ i64 ┆ y   ┆ str ┆ ped ┆ ped │
│     ┆ ds  ┆ rea ┆ --- ┆ -af ┆ -ma ┆ per ┆     ┆ rep ┆ i64 ┆ blu ┆ i64 ┆ t-a ┆ act ┆ ime ┆ --- ┆ t-r ┆ enc ┆ sse ┆ fer ┆ d   ┆     ┆     ┆ --- ┆     ┆ --- ┆ %   │
│     ┆ --- ┆ ds  ┆ i64 ┆ ter ┆ xim ┆ cen ┆     ┆ --- ┆     ┆ r   ┆     ┆ rti ┆ --- ┆ ric ┆ i64 ┆ efe ┆ e   ┆ d-r ┆ enc ┆ rea ┆     ┆     ┆ i64 ┆     ┆ i64 ┆ --- │
│     ┆ i64 ┆ --- ┆     ┆ -tr ┆ um- ┆ tag ┆     ┆ i64 ┆     ┆ --- ┆     ┆ fac ┆ i64 ┆ --- ┆     ┆ ren ┆ --- ┆ efe ┆ e   ┆ ds  ┆     ┆     ┆     ┆     ┆     ┆ str │
│     ┆     ┆ i64 ┆     ┆ unc ┆ amb ┆ e   ┆     ┆     ┆     ┆ i64 ┆     ┆ t   ┆     ┆ i64 ┆     ┆ ce  ┆ i64 ┆ ren ┆ --- ┆ +   ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ ati ┆ igu ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆     ┆ ce  ┆ i64 ┆ QC- ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ on  ┆ ou… ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆ i64 ┆     ┆ --- ┆     ┆ fai ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆ l…  ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ V1V ┆ 731 ┆ 630 ┆ 104 ┆ 104 ┆ 41  ┆ 89. ┆ 630 ┆ 299 ┆ 512 ┆ 174 ┆ 136 ┆ 0   ┆ 0   ┆ 31  ┆ 607 ┆ 143 ┆ 130 ┆ 0   ┆ 0   ┆ 164 ┆ 143 ┆ 0   ┆ 21  ┆ 100 ┆ 143 ┆ 100 │
│ 3   ┆ 78  ┆ 31  ┆     ┆     ┆     ┆ 801 ┆ 31  ┆ 2   ┆ 64  ┆     ┆ 83  ┆     ┆     ┆     ┆     ┆     ┆ 76  ┆     ┆     ┆     ┆     ┆     ┆     ┆ .00 ┆     ┆ .00 │
│     ┆     ┆     ┆     ┆     ┆     ┆ 848 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ %   ┆     ┆ %   │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [64]:
combined_df = metadata3.vstack(metadata2)
combined_df[:4]

shape: (2, 27)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ tot ┆ tot ┆ rea ┆ rea ┆ rea ┆ ret ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ tot ┆ pri ┆ sec ┆ sup ┆ map ┆ pri ┆ pri │
│ ple ┆ al- ┆ al- ┆ ds- ┆ ds- ┆ ds- ┆ ain ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ al  ┆ mar ┆ ond ┆ ple ┆ ped ┆ mar ┆ mar │
│ -id ┆ inp ┆ ret ┆ tru ┆ too ┆ exc ┆ ed- ┆ raw ┆ -re ┆ der ┆ -re ┆ deb ┆ -re ┆ hit ┆ -re ┆ chi ┆ -re ┆ hit ┆ -re ┆ mis ┆ (QC ┆ y   ┆ ary ┆ men ┆ %   ┆ y   ┆ y   │
│ --- ┆ ut- ┆ ain ┆ nca ┆ -sh ┆ eed ┆ rea ┆ --- ┆ ads ┆ ep  ┆ ads ┆ lur ┆ ads ┆ -ar ┆ ads ┆ mer ┆ ads ┆ -re ┆ ads ┆ sed ┆ -pa ┆ --- ┆ --- ┆ tar ┆ --- ┆ map ┆ map │
│ str ┆ rea ┆ ed- ┆ ted ┆ ort ┆ ing ┆ ds- ┆ i64 ┆ -de ┆ --- ┆ -de ┆ --- ┆ -hi ┆ tif ┆ -ch ┆ ic  ┆ -hi ┆ fer ┆ -mi ┆ -re ┆ sse ┆ i64 ┆ i64 ┆ y   ┆ str ┆ ped ┆ ped │
│     ┆ ds  ┆ rea ┆ --- ┆ -af ┆ -ma ┆ per ┆     ┆ rep ┆ i64 ┆ blu ┆ i64 ┆ t-a ┆ act ┆ ime ┆ --- ┆ t-r ┆ enc ┆ sse ┆ fer ┆ d   ┆     ┆     ┆ --- ┆     ┆ --- ┆ %   │
│     ┆ --- ┆ ds  ┆ i64 ┆ ter ┆ xim ┆ cen ┆     ┆ --- ┆     ┆ r   ┆     ┆ rti ┆ --- ┆ ric ┆ i64 ┆ efe ┆ e   ┆ d-r ┆ enc ┆ rea ┆     ┆     ┆ i64 ┆     ┆ i64 ┆ --- │
│     ┆ i64 ┆ --- ┆     ┆ -tr ┆ um- ┆ tag ┆     ┆ i64 ┆     ┆ --- ┆     ┆ fac ┆ i64 ┆ --- ┆     ┆ ren ┆ --- ┆ efe ┆ e   ┆ ds  ┆     ┆     ┆     ┆     ┆     ┆ str │
│     ┆     ┆ i64 ┆     ┆ unc ┆ amb ┆ e   ┆     ┆     ┆     ┆ i64 ┆     ┆ t   ┆     ┆ i64 ┆     ┆ ce  ┆ i64 ┆ ren ┆ --- ┆ +   ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ ati ┆ igu ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆     ┆ ce  ┆ i64 ┆ QC- ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ on  ┆ ou… ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆ i64 ┆     ┆ --- ┆     ┆ fai ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆ l…  ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ V1V ┆ 731 ┆ 730 ┆ 104 ┆ 104 ┆ 41  ┆ 99. ┆ 730 ┆ 299 ┆ 512 ┆ 174 ┆ 136 ┆ 0   ┆ 0   ┆ 31  ┆ 607 ┆ 143 ┆ 130 ┆ 0   ┆ 0   ┆ 164 ┆ 143 ┆ 0   ┆ 21  ┆ 100 ┆ 143 ┆ 100 │
│ 2   ┆ 76  ┆ 31  ┆     ┆     ┆     ┆ 801 ┆ 31  ┆ 2   ┆ 64  ┆     ┆ 83  ┆     ┆     ┆     ┆     ┆     ┆ 76  ┆     ┆     ┆     ┆     ┆     ┆     ┆ .00 ┆     ┆ .00 │
│     ┆     ┆     ┆     ┆     ┆     ┆ 848 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ %   ┆     ┆ %   │
│ V1V ┆ 731 ┆ 630 ┆ 104 ┆ 104 ┆ 41  ┆ 89. ┆ 630 ┆ 299 ┆ 512 ┆ 174 ┆ 136 ┆ 0   ┆ 0   ┆ 31  ┆ 607 ┆ 143 ┆ 130 ┆ 0   ┆ 0   ┆ 164 ┆ 143 ┆ 0   ┆ 21  ┆ 100 ┆ 143 ┆ 100 │
│ 3   ┆ 78  ┆ 31  ┆     ┆     ┆     ┆ 801 ┆ 31  ┆ 2   ┆ 64  ┆     ┆ 83  ┆     ┆     ┆     ┆     ┆     ┆ 76  ┆     ┆     ┆     ┆     ┆     ┆     ┆ .00 ┆     ┆ .00 │
│     ┆     ┆     ┆     ┆     ┆     ┆ 848 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ %   ┆     ┆ %   │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [65]:
metadata4 = pl.read_csv("metadata3.tsv", separator="\t", has_header=True)
metadata5 = pl.read_csv("metadata4.tsv", separator="\t", has_header=True)

In [67]:
combined_df2 = combined_df.vstack(metadata4).vstack(metadata5)
combined_df2[:4]

shape: (4, 27)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ tot ┆ tot ┆ rea ┆ rea ┆ rea ┆ ret ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ tot ┆ pri ┆ sec ┆ sup ┆ map ┆ pri ┆ pri │
│ ple ┆ al- ┆ al- ┆ ds- ┆ ds- ┆ ds- ┆ ain ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ al  ┆ mar ┆ ond ┆ ple ┆ ped ┆ mar ┆ mar │
│ -id ┆ inp ┆ ret ┆ tru ┆ too ┆ exc ┆ ed- ┆ raw ┆ -re ┆ der ┆ -re ┆ deb ┆ -re ┆ hit ┆ -re ┆ chi ┆ -re ┆ hit ┆ -re ┆ mis ┆ (QC ┆ y   ┆ ary ┆ men ┆ %   ┆ y   ┆ y   │
│ --- ┆ ut- ┆ ain ┆ nca ┆ -sh ┆ eed ┆ rea ┆ --- ┆ ads ┆ ep  ┆ ads ┆ lur ┆ ads ┆ -ar ┆ ads ┆ mer ┆ ads ┆ -re ┆ ads ┆ sed ┆ -pa ┆ --- ┆ --- ┆ tar ┆ --- ┆ map ┆ map │
│ str ┆ rea ┆ ed- ┆ ted ┆ ort ┆ ing ┆ ds- ┆ i64 ┆ -de ┆ --- ┆ -de ┆ --- ┆ -hi ┆ tif ┆ -ch ┆ ic  ┆ -hi ┆ fer ┆ -mi ┆ -re ┆ sse ┆ i64 ┆ i64 ┆ y   ┆ str ┆ ped ┆ ped │
│     ┆ ds  ┆ rea ┆ --- ┆ -af ┆ -ma ┆ per ┆     ┆ rep ┆ i64 ┆ blu ┆ i64 ┆ t-a ┆ act ┆ ime ┆ --- ┆ t-r ┆ enc ┆ sse ┆ fer ┆ d   ┆     ┆     ┆ --- ┆     ┆ --- ┆ %   │
│     ┆ --- ┆ ds  ┆ i64 ┆ ter ┆ xim ┆ cen ┆     ┆ --- ┆     ┆ r   ┆     ┆ rti ┆ --- ┆ ric ┆ i64 ┆ efe ┆ e   ┆ d-r ┆ enc ┆ rea ┆     ┆     ┆ i64 ┆     ┆ i64 ┆ --- │
│     ┆ i64 ┆ --- ┆     ┆ -tr ┆ um- ┆ tag ┆     ┆ i64 ┆     ┆ --- ┆     ┆ fac ┆ i64 ┆ --- ┆     ┆ ren ┆ --- ┆ efe ┆ e   ┆ ds  ┆     ┆     ┆     ┆     ┆     ┆ str │
│     ┆     ┆ i64 ┆     ┆ unc ┆ amb ┆ e   ┆     ┆     ┆     ┆ i64 ┆     ┆ t   ┆     ┆ i64 ┆     ┆ ce  ┆ i64 ┆ ren ┆ --- ┆ +   ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ ati ┆ igu ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆     ┆ ce  ┆ i64 ┆ QC- ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ on  ┆ ou… ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆ i64 ┆     ┆ --- ┆     ┆ fai ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆ l…  ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ V1V ┆ 731 ┆ 730 ┆ 104 ┆ 104 ┆ 41  ┆ 99. ┆ 730 ┆ 299 ┆ 512 ┆ 174 ┆ 136 ┆ 0   ┆ 0   ┆ 31  ┆ 607 ┆ 143 ┆ 130 ┆ 0   ┆ 0   ┆ 164 ┆ 143 ┆ 0   ┆ 21  ┆ 100 ┆ 143 ┆ 100 │
│ 2   ┆ 76  ┆ 31  ┆     ┆     ┆     ┆ 801 ┆ 31  ┆ 2   ┆ 64  ┆     ┆ 83  ┆     ┆     ┆     ┆     ┆     ┆ 76  ┆     ┆     ┆     ┆     ┆     ┆     ┆ .00 ┆     ┆ .00 │
│     ┆     ┆     ┆     ┆     ┆     ┆ 848 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ %   ┆     ┆ %   │
│ V1V ┆ 731 ┆ 630 ┆ 104 ┆ 104 ┆ 41  ┆ 89. ┆ 630 ┆ 299 ┆ 512 ┆ 174 ┆ 136 ┆ 0   ┆ 0   ┆ 31  ┆ 607 ┆ 143 ┆ 130 ┆ 0   ┆ 0   ┆ 164 ┆ 143 ┆ 0   ┆ 21  ┆ 100 ┆ 143 ┆ 100 │
│ 3   ┆ 78  ┆ 31  ┆     ┆     ┆     ┆ 801 ┆ 31  ┆ 2   ┆ 64  ┆     ┆ 83  ┆     ┆     ┆     ┆     ┆     ┆ 76  ┆     ┆     ┆     ┆     ┆     ┆     ┆ .00 ┆     ┆ .00 │
│     ┆     ┆     ┆     ┆     ┆     ┆ 848 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ %   ┆     ┆ %   │
│ V1V ┆ 731 ┆ 630 ┆ 104 ┆ 104 ┆ 41  ┆ 89. ┆ 630 ┆ 299 ┆ 512 ┆ 194 ┆ 136 ┆ 0   ┆ 0   ┆ 31  ┆ 607 ┆ 143 ┆ 130 ┆ 0   ┆ 0   ┆ 164 ┆ 143 ┆ 0   ┆ 21  ┆ 100 ┆ 143 ┆ 100 │
│ 4   ┆ 78  ┆ 31  ┆     ┆     ┆     ┆ 801 ┆ 31  ┆ 2   ┆ 64  ┆     ┆ 83  ┆     ┆     ┆     ┆     ┆     ┆ 75  ┆     ┆     ┆     ┆     ┆     ┆     ┆ .00 ┆     ┆ .00 │
│     ┆     ┆     ┆     ┆     ┆     ┆ 848 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ %   ┆     ┆ %   │
│ V1V ┆ 731 ┆ 630 ┆ 104 ┆ 104 ┆ 41  ┆ 89. ┆ 640 ┆ 299 ┆ 512 ┆ 174 ┆ 136 ┆ 0   ┆ 0   ┆ 31  ┆ 607 ┆ 143 ┆ 130 ┆ 0   ┆ 0   ┆ 164 ┆ 143 ┆ 0   ┆ 21  ┆ 100 ┆ 143 ┆ 100 │
│ 6   ┆ 78  ┆ 31  ┆     ┆     ┆     ┆ 801 ┆ 31  ┆ 2   ┆ 64  ┆     ┆ 83  ┆     ┆     ┆     ┆     ┆     ┆ 76  ┆     ┆     ┆     ┆     ┆     ┆     ┆ .00 ┆     ┆ .00 │
│     ┆     ┆     ┆     ┆     ┆     ┆ 848 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ %   ┆     ┆ %   │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [68]:
#read some file and then append the metadata1 dataframe to the file
combined_df2.write_csv("combined_metadata.tsv", separator="\t", has_header=True)