In [1]:
import polars as pl

In [2]:
pl.Config.set_tbl_cols(-1)  # Display all columns
pl.Config.set_tbl_rows(-1)  # Display all rows

polars.config.Config

In [3]:
#script to create a metada file for wagtail run
#inside the metadata file, we will have the following columns:
#1. sample_id
#2. total input reads (from qc reports)
#3. total retained reads (from qc reports)
#4. total retained reads percentage (#3/#2*100)
#5-18. deblur stats result
#19. total reads for mapping (from samtools flagstat reports line 1)
#20. total all mapped reads with percentage (from samtools flagstat reports line 7)
#21. total all primary mapped reads with percentage (from samtools flagstat reports line 8)

#1-18 is combining from the qc-stats report with deblur stats result
#19-21 is from samtools flagstat report and take only line 1, 7, and 8

In [3]:
#read the qc-stats report and deblur stats result
qc_stats = pl.read_csv("qc-stats.csv")
deblur_stats = pl.read_csv("deblur-stats.csv")

In [4]:
qc_stats[:4]

shape: (1, 6)
┌───────────┬─────────────────┬─────────────────┬────────────────┬────────────────┬────────────────┐
│ sample-id ┆ total-input-rea ┆ total-retained- ┆ reads-truncate ┆ reads-too-shor ┆ reads-exceedin │
│ ---       ┆ ds              ┆ reads           ┆ d              ┆ t-after-trunca ┆ g-maximum-ambi │
│ str       ┆ ---             ┆ ---             ┆ ---            ┆ tion           ┆ guou…          │
│           ┆ i64             ┆ i64             ┆ i64            ┆ ---            ┆ ---            │
│           ┆                 ┆                 ┆                ┆ i64            ┆ i64            │
╞═══════════╪═════════════════╪═════════════════╪════════════════╪════════════════╪════════════════╡
│ V1V2      ┆ 73176           ┆ 73031           ┆ 104            ┆ 104            ┆ 41             │
└───────────┴─────────────────┴─────────────────┴────────────────┴────────────────┴────────────────┘

In [5]:
#add percentage of total retained reads to the qc_stats dataframe
#calculate the total retained reads/total input reads * 100 and save it to a new column called retained-reads-percentage
qc_stats1 = qc_stats.with_columns((pl.col("total-retained-reads") / pl.col("total-input-reads") * 100).alias("retained-reads-percentage"))
qc_stats1[:4]

shape: (1, 7)
┌───────────┬──────────────┬──────────────┬──────────────┬─────────────┬─────────────┬─────────────┐
│ sample-id ┆ total-input- ┆ total-retain ┆ reads-trunca ┆ reads-too-s ┆ reads-excee ┆ retained-re │
│ ---       ┆ reads        ┆ ed-reads     ┆ ted          ┆ hort-after- ┆ ding-maximu ┆ ads-percent │
│ str       ┆ ---          ┆ ---          ┆ ---          ┆ truncation  ┆ m-ambiguou… ┆ age         │
│           ┆ i64          ┆ i64          ┆ i64          ┆ ---         ┆ ---         ┆ ---         │
│           ┆              ┆              ┆              ┆ i64         ┆ i64         ┆ f64         │
╞═══════════╪══════════════╪══════════════╪══════════════╪═════════════╪═════════════╪═════════════╡
│ V1V2      ┆ 73176        ┆ 73031        ┆ 104          ┆ 104         ┆ 41          ┆ 99.801848   │
└───────────┴──────────────┴──────────────┴──────────────┴─────────────┴─────────────┴─────────────┘

In [6]:
deblur_stats[:4]

shape: (1, 14)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┬───────┬───────┬───────┬───────┬───────┬───────┐
│ sam ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ reads- ┆ uniqu ┆ reads ┆ uniqu ┆ reads ┆ uniqu ┆ reads │
│ ple ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ hit-ar ┆ e-rea ┆ -chim ┆ e-rea ┆ -hit- ┆ e-rea ┆ -miss │
│ -id ┆ raw ┆ -re ┆ der ┆ -re ┆ deb ┆ -re ┆ tifact ┆ ds-ch ┆ eric  ┆ ds-hi ┆ refer ┆ ds-mi ┆ ed-re │
│ --- ┆ --- ┆ ads ┆ ep  ┆ ads ┆ lur ┆ ads ┆ ---    ┆ imeri ┆ ---   ┆ t-ref ┆ ence  ┆ ssed- ┆ feren │
│ str ┆ i64 ┆ -de ┆ --- ┆ -de ┆ --- ┆ -hi ┆ i64    ┆ c     ┆ i64   ┆ erenc ┆ ---   ┆ refer ┆ ce    │
│     ┆     ┆ rep ┆ i64 ┆ blu ┆ i64 ┆ t-a ┆        ┆ ---   ┆       ┆ e     ┆ i64   ┆ ence  ┆ ---   │
│     ┆     ┆ --- ┆     ┆ r   ┆     ┆ rti ┆        ┆ i64   ┆       ┆ ---   ┆       ┆ ---   ┆ i64   │
│     ┆     ┆ i64 ┆     ┆ --- ┆     ┆ fac ┆        ┆       ┆       ┆ i64   ┆       ┆ i64   ┆       │
│     ┆     ┆     ┆     ┆ i64 ┆     ┆ t   ┆        ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆        ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆        ┆       ┆       ┆       ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╡
│ V1V ┆ 730 ┆ 299 ┆ 512 ┆ 174 ┆ 136 ┆ 0   ┆ 0      ┆ 31    ┆ 607   ┆ 143   ┆ 13076 ┆ 0     ┆ 0     │
│ 2   ┆ 31  ┆ 2   ┆ 64  ┆     ┆ 83  ┆     ┆        ┆       ┆       ┆       ┆       ┆       ┆       │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴────────┴───────┴───────┴───────┴───────┴───────┴───────┘

In [9]:
#combine the qc_stats1 and deblur_stats dataframe
#we will use the sample-id column to join the two dataframes
metadata = qc_stats1.join(deblur_stats, on="sample-id")
metadata[:4]

shape: (1, 20)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ tot ┆ tot ┆ rea ┆ rea ┆ rea ┆ ret ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea │
│ ple ┆ al- ┆ al- ┆ ds- ┆ ds- ┆ ds- ┆ ain ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- │
│ -id ┆ inp ┆ ret ┆ tru ┆ too ┆ exc ┆ ed- ┆ raw ┆ -re ┆ der ┆ -re ┆ deb ┆ -re ┆ hit ┆ -re ┆ chi ┆ -re ┆ hit ┆ -re ┆ mis │
│ --- ┆ ut- ┆ ain ┆ nca ┆ -sh ┆ eed ┆ rea ┆ --- ┆ ads ┆ ep  ┆ ads ┆ lur ┆ ads ┆ -ar ┆ ads ┆ mer ┆ ads ┆ -re ┆ ads ┆ sed │
│ str ┆ rea ┆ ed- ┆ ted ┆ ort ┆ ing ┆ ds- ┆ i64 ┆ -de ┆ --- ┆ -de ┆ --- ┆ -hi ┆ tif ┆ -ch ┆ ic  ┆ -hi ┆ fer ┆ -mi ┆ -re │
│     ┆ ds  ┆ rea ┆ --- ┆ -af ┆ -ma ┆ per ┆     ┆ rep ┆ i64 ┆ blu ┆ i64 ┆ t-a ┆ act ┆ ime ┆ --- ┆ t-r ┆ enc ┆ sse ┆ fer │
│     ┆ --- ┆ ds  ┆ i64 ┆ ter ┆ xim ┆ cen ┆     ┆ --- ┆     ┆ r   ┆     ┆ rti ┆ --- ┆ ric ┆ i64 ┆ efe ┆ e   ┆ d-r ┆ enc │
│     ┆ i64 ┆ --- ┆     ┆ -tr ┆ um- ┆ tag ┆     ┆ i64 ┆     ┆ --- ┆     ┆ fac ┆ i64 ┆ --- ┆     ┆ ren ┆ --- ┆ efe ┆ e   │
│     ┆     ┆ i64 ┆     ┆ unc ┆ amb ┆ e   ┆     ┆     ┆     ┆ i64 ┆     ┆ t   ┆     ┆ i64 ┆     ┆ ce  ┆ i64 ┆ ren ┆ --- │
│     ┆     ┆     ┆     ┆ ati ┆ igu ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆     ┆ ce  ┆ i64 │
│     ┆     ┆     ┆     ┆ on  ┆ ou… ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆ i64 ┆     ┆ --- ┆     │
│     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     │
│     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ V1V ┆ 731 ┆ 730 ┆ 104 ┆ 104 ┆ 41  ┆ 99. ┆ 730 ┆ 299 ┆ 512 ┆ 174 ┆ 136 ┆ 0   ┆ 0   ┆ 31  ┆ 607 ┆ 143 ┆ 130 ┆ 0   ┆ 0   │
│ 2   ┆ 76  ┆ 31  ┆     ┆     ┆     ┆ 801 ┆ 31  ┆ 2   ┆ 64  ┆     ┆ 83  ┆     ┆     ┆     ┆     ┆     ┆ 76  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ 848 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [12]:
#read the samtools flagstat report
metadata2 = pl.read_csv("V1V2_2_metadata.tsv", separator= '\t', has_header=True)
metadata2[:4]

shape: (1, 6)
┌───────────┬─────────────┬──────────────┬────────────────┬────────────────────┬──────────────┐
│ sample-id ┆ total reads ┆ mapped reads ┆ unmapped reads ┆ mapping percentage ┆ average mapq │
│ ---       ┆ ---         ┆ ---          ┆ ---            ┆ ---                ┆ ---          │
│ str       ┆ i64         ┆ i64          ┆ i64            ┆ f64                ┆ f64          │
╞═══════════╪═════════════╪══════════════╪════════════════╪════════════════════╪══════════════╡
│ V1V2      ┆ 129         ┆ 129          ┆ 0              ┆ 100.0              ┆ 0.356589     │
└───────────┴─────────────┴──────────────┴────────────────┴────────────────────┴──────────────┘

In [13]:
#combine the metadata and metadata2 dataframe
#we will use the sample-id column to join the two dataframes
metadata3 = metadata.join(metadata2, on="sample-id")
metadata3[:4]

shape: (1, 25)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ tot ┆ tot ┆ rea ┆ rea ┆ rea ┆ ret ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ uni ┆ rea ┆ tot ┆ map ┆ unm ┆ map ┆ ave │
│ ple ┆ al- ┆ al- ┆ ds- ┆ ds- ┆ ds- ┆ ain ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ que ┆ ds- ┆ al  ┆ ped ┆ app ┆ pin ┆ rag │
│ -id ┆ inp ┆ ret ┆ tru ┆ too ┆ exc ┆ ed- ┆ raw ┆ -re ┆ der ┆ -re ┆ deb ┆ -re ┆ hit ┆ -re ┆ chi ┆ -re ┆ hit ┆ -re ┆ mis ┆ rea ┆ rea ┆ ed  ┆ g   ┆ e   │
│ --- ┆ ut- ┆ ain ┆ nca ┆ -sh ┆ eed ┆ rea ┆ --- ┆ ads ┆ ep  ┆ ads ┆ lur ┆ ads ┆ -ar ┆ ads ┆ mer ┆ ads ┆ -re ┆ ads ┆ sed ┆ ds  ┆ ds  ┆ rea ┆ per ┆ map │
│ str ┆ rea ┆ ed- ┆ ted ┆ ort ┆ ing ┆ ds- ┆ i64 ┆ -de ┆ --- ┆ -de ┆ --- ┆ -hi ┆ tif ┆ -ch ┆ ic  ┆ -hi ┆ fer ┆ -mi ┆ -re ┆ --- ┆ --- ┆ ds  ┆ cen ┆ q   │
│     ┆ ds  ┆ rea ┆ --- ┆ -af ┆ -ma ┆ per ┆     ┆ rep ┆ i64 ┆ blu ┆ i64 ┆ t-a ┆ act ┆ ime ┆ --- ┆ t-r ┆ enc ┆ sse ┆ fer ┆ i64 ┆ i64 ┆ --- ┆ tag ┆ --- │
│     ┆ --- ┆ ds  ┆ i64 ┆ ter ┆ xim ┆ cen ┆     ┆ --- ┆     ┆ r   ┆     ┆ rti ┆ --- ┆ ric ┆ i64 ┆ efe ┆ e   ┆ d-r ┆ enc ┆     ┆     ┆ i64 ┆ e   ┆ f64 │
│     ┆ i64 ┆ --- ┆     ┆ -tr ┆ um- ┆ tag ┆     ┆ i64 ┆     ┆ --- ┆     ┆ fac ┆ i64 ┆ --- ┆     ┆ ren ┆ --- ┆ efe ┆ e   ┆     ┆     ┆     ┆ --- ┆     │
│     ┆     ┆ i64 ┆     ┆ unc ┆ amb ┆ e   ┆     ┆     ┆     ┆ i64 ┆     ┆ t   ┆     ┆ i64 ┆     ┆ ce  ┆ i64 ┆ ren ┆ --- ┆     ┆     ┆     ┆ f64 ┆     │
│     ┆     ┆     ┆     ┆ ati ┆ igu ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆     ┆ ce  ┆ i64 ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ on  ┆ ou… ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆ i64 ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ V1V ┆ 731 ┆ 730 ┆ 104 ┆ 104 ┆ 41  ┆ 99. ┆ 730 ┆ 299 ┆ 512 ┆ 174 ┆ 136 ┆ 0   ┆ 0   ┆ 31  ┆ 607 ┆ 143 ┆ 130 ┆ 0   ┆ 0   ┆ 129 ┆ 129 ┆ 0   ┆ 100 ┆ 0.3 │
│ 2   ┆ 76  ┆ 31  ┆     ┆     ┆     ┆ 801 ┆ 31  ┆ 2   ┆ 64  ┆     ┆ 83  ┆     ┆     ┆     ┆     ┆     ┆ 76  ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆ 565 │
│     ┆     ┆     ┆     ┆     ┆     ┆ 848 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 89  │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [14]:
#read some file and then append the metadata1 dataframe to the file
metadata3.write_csv("metadata_combined-mappy.tsv", separator="\t", has_header=True)