In [1]:
import polars as pl
import mappy as mp
import os
from collections import Counter
from collections import OrderedDict

In [4]:
input ='/home/n11702427/m/users/r_nurdiansyah/wagtail/testing/3_mappy/dna-sequences.fasta'
output_align='/home/n11702427/m/users/r_nurdiansyah/wagtail/testing/3_mappy/align'
output_meta='/home/n11702427/m/users/r_nurdiansyah/wagtail/testing/3_mappy/meta'
index='/home/n11702427/m/users/r_nurdiansyah/wagtail/0_database/danica.mmi'

In [3]:
#setting class so it can be used
#dataclass
class AmpliconDataset:
    input_file: str = None
    basename: str = None
    output_directory: str = None

In [3]:
#read index to mappy
ref = mp.Aligner(index, preset = 'sr')
if not ref: raise Exception("ERROR: failed to load/build index")
#print to console if index is loaded from the file

In [38]:
print(mp.__file__)

/mnt/hpccs01/work/microbiome/users/r_nurdiansyah/e/minimap-update/lib/python3.12/site-packages/mappy.cpython-312-x86_64-linux-gnu.so

In [5]:
#testing mappy to read fastq
for name, seq, qual in mp.fastx_read(input, read_comment=False):
    #print("{}\t{}\t{}".format(name, seq, qual))
    r1_name = name
    print(r1_name)

1c952ffa899157451e1a0803a6e7d1be
961fd2d00cf9d8631a7bf2e1e954678b
e2c0a94741782377cd3808323213edb7
9508d1e293eb48991dbcbed8ac8cf57d
d4c2eddd7f6efef8a159f05deecf7234
d5d03ff437157e429bf2ee3fe36082cb
b8b28a281d89e46e6e098250eb2690a8
3b3306459720de37604f4ac82d92fed8
fad117348b9cb3cb3f9b3a41f1341ffa
58b2da87846b2cf5f2002bf364e7cd38
774988575190ff17b5c62a5c91b0f574
d0fdfeb3138c01a6d3bdfc9575c24a75
ceb756736a42eac0b088578abde942b9
97f97975d309adf303f8248cc7cfc7a9
e4dac646715b26b2149e30e02581b3ca
b7a618cc2e2f6c22f533ce5ff8a86a9c
8a972df62756e85e331fa195231167f9
7722883efb81040117fcc5c24b74ab22
17109367a25b5799be057e9b4b079d8f
296b7b1fc7af0d48f3c4a5002b7ea839
c2705de3ba6a57e6776d68a10ae9e784
62021d6c403b0e03b1597ab090ad300d
121b6c54066c48c42f35313ae229e9d5
5f63590a17f64dba1c57a5b5ca30ac73
e98c584dbecf9c8de3d4cdc09f0ff091
096a6461bcb2745a2388b4044f52d5b1
8b8909155dd0cc40fa6b00c592c4578d
a7bd97c0939453694ec31e6e796c9e43
16b156381191fe61f7e34dc36198d633
c41e1bbde55fe9e7d60c035b9a2afde5
cce5a8ae8184d7590831c2c809762756
79f0d7d17c185b5f8f72bc08bf915b4e
5c8c6787af4b521fb37027594dff218c
3815981f5eec3041379a2e3ea519b82e
4a7f88664120e63e12174c44a7ccbd80
6e35ca0fa29dc527f3d610aa506f40e9
1feb3bba5bdbbc96a75d0034e7def359
670f7a3636c285cf24306d9fb32ec160
686d8474cd3bb11c40473aaecacff54b
44a7bd3a103f787fd1a4f10b849e4779
9b8f786d33ae3b48af0ccdf1a3887470
62b5502e9a2a38e191be617f8e41c49d
b0b6ea60d97a09e8aecedc106773f8d2
6a7871771a7298801ed741013bc1f655
140c078407243d2b9de27f95a29741b4
c5fdaebe2a3686a2f529ce42647e6198
533f2965d7b74615a2586c6ee7e489d8
d6cdf7c7a0f9518059241571562be4db
2368c3d135663592c0226bd9d2d2da10
7b6335cd7e10e1422b280eb123f83d7e
3364df7b0b11987ffff16f158caf4795
af0ae3870adcc2a98361d9ed76d367d3
29e605fb669727fb368d49b264620c93
68efa12a8aa92e52f9e2078b372cc8ec
0606ca488fc71a9359666498197813f5
6ec1062f7ec46a4aedacaebe23445395
38065c6f14c9cfd5cd831c1ee8739a8c
63167510157545026d22f86a58a6b818
f97e0d3353cd4b86be84fb58e92867c8
520df4651a2f3f3a9e99d6b07969f019
64cbc0225f5f09e744755506cc90baa6
d91d0ce8bf3a1f10feda6bee296b449c
833a45e3f0e45f8553c5f0f7e55f11b4
cc313ec8d74285f978ad386dacec5fea
4532835fdc1e9f5673fe24ca3b590104
2bdf213310014e5ac7cff19070f2a0e2
f0e0817a4425d33de64a0e325309935a
464561163f189f00c02d8085bd192681
513dcffac5b0257f1d68a94867fda032
b2cc48b8e7849cec6ed3fdbaba6839f6
ffe5fc0368a17ee8db139acb6fecd132
2995e0dfda3948a678dc76495e2977fa
1f4df7b70c591366724ce2f002c0e877
80a2a44dd7f3dc93107d0cc94a748c94
118cb338c2306df849472a6c8949a511
6416b4cf981f06a412046e022c4084d3
6c88f8cd0621b18fb37c4af744b40adf
170520bf35dcae32543275d9f55b7908
474ec314e445ffa9af7a68fdb79ed4c5
50fbdfbcc1b08f6fb19a458464c25ff2
3428b628ce1aecd60fb77d854cc1328f
73b0292db3672fe67d35c3bba38a3ba4
657ec1d9c6cd93d5b328d65c8f25ab3b
bfbd43bd679c075d6bb3c89a3b9fad9e
6433e82a896bc5d603961f41e9cc74b0
846aa1fa794afff39e50eb7604ffd51e
e17c85a18deaf4ed2463499e1553872d
b7f76451adeac7922326704b5c34f73c
8671d1cbc48f61cadeb28c7c0b1ac9f6
4acf284a063b1d12894588c9b381e76e
71eb7967f7bc3512b35eab1952e3f94f
94a6995e9470f7c9ca7604d7ba315a47
d6c4f461b70d4ca382fded9e58a71902
f4fda8ddff97763c475456aaa1d1382d
d2fbdbae74d397d08a87cec7b0f6444a
c56355c5e7564a78d9fc80a9043919a2
9cec45cc581eaa03c130f6f1477a9a09
7abde694dfd2e2a6978bc7847042a97e
1b7d2ec48a8e830ca7bc388c2caa627c
905df73acdbb853f5dc5a3bd7e6193bb
404caa5f5f66a8079657091d547bde5f
161b64b73b02e7b223065d61966ed942
9a2c3fc68d3783a3e63896aa92e71ad1
4f5e3d3af641305ff0fce18a404508ea
1ea8d968f45489227d4e5f422f3e2418
46eb6b99d8663bb8d68c438b2ff15e16
5f0bbd38ab701ce3f09699715719fda5
610bdf0c110a05605b8dcbda9723cbd4
edc21bb219b228ae2fc8dd47bb30b0f3
246d57387441b5e2cb9e30ec2e7e7a4c
cb992e4afb270c1edc3aeaebb3869f06
754782ceab81596ae07dc5fc0870c7e8
aa5bcfc7d7da3bd0706af1ef9c7678e7
352b968009f49c39f5b22f840bbbd25f
e154edb81ec80f21e036f7aa862fe4a1
4a4d8ffcca64284cb21da4446f0b98f6
2889bb7d750a6398a62afb8bb634b591
5fa838c8d0afe988f17310370fc645b0
0b3214ba74e549c8695602813f08ea56
f0cccac195182770a309de8b8c912976
b82fac57d1ffe12abc91e6474f4a8565
81914f82b93e19575ff4c0142697c2ab
69d18bb1d05ccaabe9ca6252a6b4f971
16eb98ccd826e972caa22eb46b172e50
faa404f26355ade0452744f952b68072
433fb165118a2fa968618a0b7d914a84
aa77e018552a2cc9f2e708c55c974a47
3966eca3da3f39e0d9905150e0fa5f15
1f9e3d4552fec145e4e1a72089072259

In [6]:
# Initialize counters -> for metadata
total_mapq = 0
alignment_counter = Counter()

In [30]:
result_per_i = {}
for name, seq, qual in mp.fastx_read(input, read_comment=False):
    is_mapped = False #to track duplicates
    #for hits in ref.map(seq, cs=True, MD=True):
    for hits in ref.map(seq):
        if hits.is_primary:
            result_per_i[name] = (hits.ctg)
            alignment_counter['mapped'] += 1
            total_mapq += hits.mapq
            is_mapped = True
            break # Only consider primary alignment
        else:
            alignment_counter['unmapped'] += 1
    #count the number of hits using Counter
#ctg_counts = Counter(result_per_i.values())    
print(result_per_i)

{'1c952ffa899157451e1a0803a6e7d1be': 'FLASV871300.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_24189;', '961fd2d00cf9d8631a7bf2e1e954678b': 'FLASV1017960.1381;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Enterococcaceae,g:Enterococcus,s:MFD_s_1017960;', 'e2c0a94741782377cd3808323213edb7': 'FLASV832231.1372;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Staphylococcales,f:Staphylococcaceae,g:Staphylococcus,s:MFD_s_126847;', '9508d1e293eb48991dbcbed8ac8cf57d': 'FLASV871300.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_24189;', 'd4c2eddd7f6efef8a159f05deecf7234': 'FLASV1017960.1381;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Enterococcaceae,g:Enterococcus,s:MFD_s_1017960;', 'd5d03ff437157e429bf2ee3fe36082cb': 'FLASV662431.1374;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Pseudomonadales,f:Hahellaceae,g:Hahella,s:MFD_s_26319;', 'b8b28a281d89e46e6e098250eb2690a8': 'FLASV832231.1372;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Staphylococcales,f:Staphylococcaceae,g:Staphylococcus,s:MFD_s_126847;', '3b3306459720de37604f4ac82d92fed8': 'FLASV871300.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_24189;', 'fad117348b9cb3cb3f9b3a41f1341ffa': 'FLASV871300.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_24189;', '58b2da87846b2cf5f2002bf364e7cd38': 'FLASV1017960.1381;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Enterococcaceae,g:Enterococcus,s:MFD_s_1017960;', '774988575190ff17b5c62a5c91b0f574': 'FLASV1017960.1381;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Enterococcaceae,g:Enterococcus,s:MFD_s_1017960;', 'd0fdfeb3138c01a6d3bdfc9575c24a75': 'FLASV832231.1372;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Staphylococcales,f:Staphylococcaceae,g:Staphylococcus,s:MFD_s_126847;', 'ceb756736a42eac0b088578abde942b9': 'FLASV817681.1349;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Pseudomonadales,f:Pseudohongiellaceae,g:Pseudohongiella,s:MFD_s_817681;', '97f97975d309adf303f8248cc7cfc7a9': 'FLASV1008642.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Salmonella,s:MFD_s_69746;', 'e4dac646715b26b2149e30e02581b3ca': 'FLASV518250.1366;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Pseudomonadales,f:Moraxellaceae,g:Agitococcus_lubricus_group,s:MFD_s_2007;', 'b7a618cc2e2f6c22f533ce5ff8a86a9c': 'FLASV845393.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Listeriaceae,g:Listeria,s:MFD_s_286000;', '8a972df62756e85e331fa195231167f9': 'FLASV886356.1357;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Pseudomonadales,f:Pseudomonadaceae,g:Pseudomonas,s:Pseudomonas_aeruginosa;', '7722883efb81040117fcc5c24b74ab22': 'FLASV784595.1345;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Morganellaceae,g:Arsenophonus,s:MFD_s_784595;', '17109367a25b5799be057e9b4b079d8f': 'FLASV1008642.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Salmonella,s:MFD_s_69746;', '296b7b1fc7af0d48f3c4a5002b7ea839': 'FLASV845393.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Listeriaceae,g:Listeria,s:MFD_s_286000;', 'c2705de3ba6a57e6776d68a10ae9e784': 'FLASV883688.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Escherichia-Shigella,s:MFD_s_383;', '62021d6c403b0e03b1597ab090ad300d': 'FLASV662431.1374;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Pseudomonadales,f:Hahellaceae,g:Hahella,s:MFD_s_26319;', '121b6c54066c48c42f35313ae229e9d5': 'FLASV916992.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;', '5f63590a17f64dba1c57a5b5ca30ac73': 'FLASV876198.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Escherichia-Shigella,s:MFD_s_383;', 'e98c584dbecf9c8de3d4cdc09f0ff091': 'FLASV884662.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Listeriaceae,g:Listeria,s:MFD_s_286000;', '096a6461bcb2745a2388b4044f52d5b1': 'FLASV662431.1374;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Pseudomonadales,f:Hahellaceae,g:Hahella,s:MFD_s_26319;', '8b8909155dd0cc40fa6b00c592c4578d': 'FLASV870482.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_24189;', 'a7bd97c0939453694ec31e6e796c9e43': 'FLASV884662.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Listeriaceae,g:Listeria,s:MFD_s_286000;', '16b156381191fe61f7e34dc36198d633': 'FLASV531209.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;', 'c41e1bbde55fe9e7d60c035b9a2afde5': 'FLASV884662.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Listeriaceae,g:Listeria,s:MFD_s_286000;', 'cce5a8ae8184d7590831c2c809762756': 'FLASV414129.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;', '79f0d7d17c185b5f8f72bc08bf915b4e': 'FLASV883688.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Escherichia-Shigella,s:MFD_s_383;', '5c8c6787af4b521fb37027594dff218c': 'FLASV873342.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Escherichia-Shigella,s:MFD_s_1065;', '3815981f5eec3041379a2e3ea519b82e': 'FLASV916992.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;', '4a7f88664120e63e12174c44a7ccbd80': 'FLASV825639.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:MFD_s_825639;', '6e35ca0fa29dc527f3d610aa506f40e9': 'FLASV825639.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:MFD_s_825639;', '1feb3bba5bdbbc96a75d0034e7def359': 'FLASV784595.1345;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Morganellaceae,g:Arsenophonus,s:MFD_s_784595;', '670f7a3636c285cf24306d9fb32ec160': 'FLASV414129.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;', '686d8474cd3bb11c40473aaecacff54b': 'FLASV870482.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_24189;', '44a7bd3a103f787fd1a4f10b849e4779': 'FLASV825639.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:MFD_s_825639;', '9b8f786d33ae3b48af0ccdf1a3887470': 'FLASV876198.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Escherichia-Shigella,s:MFD_s_383;', '62b5502e9a2a38e191be617f8e41c49d': 'FLASV870482.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_24189;', 'b0b6ea60d97a09e8aecedc106773f8d2': 'FLASV876361.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;', '6a7871771a7298801ed741013bc1f655': 'FLASV873342.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Escherichia-Shigella,s:MFD_s_1065;', '140c078407243d2b9de27f95a29741b4': 'FLASV883688.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Escherichia-Shigella,s:MFD_s_383;', 'c5fdaebe2a3686a2f529ce42647e6198': 'FLASV414129.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;', '533f2965d7b74615a2586c6ee7e489d8': 'FLASV876361.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;', 'd6cdf7c7a0f9518059241571562be4db': 'FLASV883688.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Escherichia-Shigella,s:MFD_s_383;', '2368c3d135663592c0226bd9d2d2da10': 'FLASV916992.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;', '7b6335cd7e10e1422b280eb123f83d7e': 'FLASV873342.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Escherichia-Shigella,s:MFD_s_1065;', '3364df7b0b11987ffff16f158caf4795': 'FLASV876361.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;', 'af0ae3870adcc2a98361d9ed76d367d3': 'FLASV414129.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;', '29e605fb669727fb368d49b264620c93': 'FLASV825639.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:MFD_s_825639;', '68efa12a8aa92e52f9e2078b372cc8ec': 'FLASV531209.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;', '0606ca488fc71a9359666498197813f5': 'FLASV884662.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Listeriaceae,g:Listeria,s:MFD_s_286000;', '6ec1062f7ec46a4aedacaebe23445395': 'FLASV531209.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;', '38065c6f14c9cfd5cd831c1ee8739a8c': 'FLASV964003.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Escherichia-Shigella,s:MFD_s_889512;', '63167510157545026d22f86a58a6b818': 'FLASV873342.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Escherichia-Shigella,s:MFD_s_1065;', 'f97e0d3353cd4b86be84fb58e92867c8': 'FLASV876361.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;', '520df4651a2f3f3a9e99d6b07969f019': 'FLASV883688.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Escherichia-Shigella,s:MFD_s_383;', '64cbc0225f5f09e744755506cc90baa6': 'FLASV891861.1383;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Enterococcaceae,g:Enterococcus,s:MFD_s_891861;', 'd91d0ce8bf3a1f10feda6bee296b449c': 'FLASV148929.1366;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Pseudomonadales,f:Moraxellaceae,g:Agitococcus_lubricus_group,s:MFD_s_2007;', '833a45e3f0e45f8553c5f0f7e55f11b4': 'FLASV901271.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Listeriaceae,g:Listeria,s:MFD_s_286000;', 'cc313ec8d74285f978ad386dacec5fea': 'FLASV966006.1359;tax=d:Bacteria,p:Bacteroidota,c:Bacteroidia,o:Bacteroidales,f:Bacteroidaceae,g:Bacteroides,s:MFD_s_966006;', '4532835fdc1e9f5673fe24ca3b590104': 'FLASV336434.1381;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Enterococcaceae,g:Enterococcus,s:Enterococcus_faecalis;', '2bdf213310014e5ac7cff19070f2a0e2': 'FLASV986879.1380;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Enterococcaceae,g:Enterococcus,s:Enterococcus_faecalis;', 'f0e0817a4425d33de64a0e325309935a': 'FLASV871303.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;', '464561163f189f00c02d8085bd192681': 'FLASV941033.1359;tax=d:Bacteria,p:Bacteroidota,c:Bacteroidia,o:Bacteroidales,f:Bacteroidaceae,g:Bacteroides,s:MFD_s_941033;', '513dcffac5b0257f1d68a94867fda032': 'FLASV891861.1383;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Enterococcaceae,g:Enterococcus,s:MFD_s_891861;', 'b2cc48b8e7849cec6ed3fdbaba6839f6': 'FLASV543385.1344;tax=d:Bacteria,p:Firmicutes,c:Clostridia,o:Christensenellales,f:Christensenellaceae,g:Christensenellaceae_R-7_group,s:MFD_s_3976;', 'ffe5fc0368a17ee8db139acb6fecd132': 'FLASV851631.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;', '2995e0dfda3948a678dc76495e2977fa': 'FLASV759664.1354;tax=d:Bacteria,p:Firmicutes,c:Clostridia,o:Lachnospirales,f:Lachnospiraceae,g:Anaerostipes,s:Anaerostipes_hadrus;', '1f4df7b70c591366724ce2f002c0e877': 'FLASV1001192.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Salmonella,s:MFD_s_69746;', '80a2a44dd7f3dc93107d0cc94a748c94': 'FLASV916969.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;', '118cb338c2306df849472a6c8949a511': 'FLASV877831.1465;tax=d:Bacteria,p:Firmicutes,c:Clostridia,o:Clostridiales,f:Clostridiaceae,g:Clostridium_sensu_stricto_18,s:MFD_s_136;', '6416b4cf981f06a412046e022c4084d3': 'FLASV886356.1357;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Pseudomonadales,f:Pseudomonadaceae,g:Pseudomonas,s:Pseudomonas_aeruginosa;', '6c88f8cd0621b18fb37c4af744b40adf': 'FLASV975314.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Escherichia-Shigella,s:MFD_s_383;', '170520bf35dcae32543275d9f55b7908': 'FLASV974262.1372;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Staphylococcales,f:Staphylococcaceae,g:Staphylococcus,s:MFD_s_126847;', '474ec314e445ffa9af7a68fdb79ed4c5': 'FLASV948923.1360;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Escherichia-Shigella,s:MFD_s_948923;', '50fbdfbcc1b08f6fb19a458464c25ff2': 'FLASV979322.1399;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:MFD_s_979322;', '3428b628ce1aecd60fb77d854cc1328f': 'FLASV998171.1356;tax=d:Bacteria,p:Firmicutes,c:Clostridia,o:Lachnospirales,f:Lachnospiraceae,g:Agathobacter,s:MFD_s_998171;', '73b0292db3672fe67d35c3bba38a3ba4': 'FLASV1030103.1353;tax=d:Bacteria,p:Firmicutes,c:Clostridia,o:Oscillospirales,f:Oscillospiraceae,g:UCG-005,s:MFD_s_1030103;', '657ec1d9c6cd93d5b328d65c8f25ab3b': 'FLASV891861.1383;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Enterococcaceae,g:Enterococcus,s:MFD_s_891861;', 'bfbd43bd679c075d6bb3c89a3b9fad9e': 'FLASV982467.1357;tax=d:Bacteria,p:Firmicutes,c:Clostridia,o:Oscillospirales,f:Ruminococcaceae,g:Subdoligranulum,s:MFD_s_982467;', '6433e82a896bc5d603961f41e9cc74b0': 'FLASV819600.1381;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Enterococcaceae,g:Enterococcus,s:Enterococcus_faecalis;', '846aa1fa794afff39e50eb7604ffd51e': 'FLASV876198.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Escherichia-Shigella,s:MFD_s_383;', 'e17c85a18deaf4ed2463499e1553872d': 'FLASV819669.1397;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:MFD_s_819669;', 'b7f76451adeac7922326704b5c34f73c': 'FLASV889158.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Listeriaceae,g:Listeria,s:MFD_s_286000;', '8671d1cbc48f61cadeb28c7c0b1ac9f6': 'FLASV916992.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;', '4acf284a063b1d12894588c9b381e76e': 'FLASV126318.1354;tax=d:Bacteria,p:Firmicutes,c:Clostridia,o:Lachnospirales,f:Lachnospiraceae,g:Anaerostipes,s:Anaerostipes_hadrus;', '71eb7967f7bc3512b35eab1952e3f94f': 'FLASV910107.1357;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Pseudomonadales,f:Pseudomonadaceae,g:Pseudomonas,s:Pseudomonas_aeruginosa;', '94a6995e9470f7c9ca7604d7ba315a47': 'FLASV30172.1359;tax=d:Bacteria,p:Bacteroidota,c:Bacteroidia,o:Bacteroidales,f:Bacteroidaceae,g:Bacteroides,s:Bacteroides_xylanisolvens;', 'd6c4f461b70d4ca382fded9e58a71902': 'FLASV821800.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_24189;', 'f4fda8ddff97763c475456aaa1d1382d': 'FLASV518250.1366;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Pseudomonadales,f:Moraxellaceae,g:Agitococcus_lubricus_group,s:MFD_s_2007;', 'd2fbdbae74d397d08a87cec7b0f6444a': 'FLASV970184.1352;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Erysipelotrichales,f:Erysipelatoclostridiaceae,g:Erysipelatoclostridium,s:MFD_s_970184;', 'c56355c5e7564a78d9fc80a9043919a2': 'FLASV1011158.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Pseudomonadales,f:Pseudomonadaceae,g:Pseudomonas,s:MFD_s_1011158;', '9cec45cc581eaa03c130f6f1477a9a09': 'FLASV893164.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_787515;', '7abde694dfd2e2a6978bc7847042a97e': 'FLASV858257.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_24189;', '1b7d2ec48a8e830ca7bc388c2caa627c': 'FLASV122072.1353;tax=d:Bacteria,p:Firmicutes,c:Clostridia,o:Lachnospirales,f:Lachnospiraceae,g:Fusicatenibacter,s:Fusicatenibacter_saccharivorans;', '905df73acdbb853f5dc5a3bd7e6193bb': 'FLASV934985.1369;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_24189;', '404caa5f5f66a8079657091d547bde5f': 'FLASV934795.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_787515;', '161b64b73b02e7b223065d61966ed942': 'FLASV336434.1381;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Enterococcaceae,g:Enterococcus,s:Enterococcus_faecalis;', '9a2c3fc68d3783a3e63896aa92e71ad1': 'FLASV336434.1381;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Enterococcaceae,g:Enterococcus,s:Enterococcus_faecalis;', '4f5e3d3af641305ff0fce18a404508ea': 'FLASV970677.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Listeriaceae,g:Listeria,s:MFD_s_286000;', '1ea8d968f45489227d4e5f422f3e2418': 'FLASV1002622.1372;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Staphylococcales,f:Staphylococcaceae,g:Staphylococcus,s:MFD_s_126847;', '46eb6b99d8663bb8d68c438b2ff15e16': 'FLASV780103.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Salmonella,s:MFD_s_69746;', '5f0bbd38ab701ce3f09699715719fda5': 'FLASV981243.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Escherichia-Shigella,s:MFD_s_383;', '610bdf0c110a05605b8dcbda9723cbd4': 'FLASV813265.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Listeriaceae,g:Listeria,s:MFD_s_286000;', 'edc21bb219b228ae2fc8dd47bb30b0f3': 'FLASV934795.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_787515;', '246d57387441b5e2cb9e30ec2e7e7a4c': 'FLASV786295.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Listeriaceae,g:Listeria,s:MFD_s_286000;', 'cb992e4afb270c1edc3aeaebb3869f06': 'FLASV813265.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Listeriaceae,g:Listeria,s:MFD_s_286000;', '754782ceab81596ae07dc5fc0870c7e8': 'FLASV1017348.1371;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Staphylococcales,f:Staphylococcaceae,g:Staphylococcus,s:MFD_s_126847;', 'aa5bcfc7d7da3bd0706af1ef9c7678e7': 'FLASV934985.1369;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_24189;', '352b968009f49c39f5b22f840bbbd25f': 'FLASV821309.1378;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_24189;', 'e154edb81ec80f21e036f7aa862fe4a1': 'FLASV858257.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_24189;', '4a4d8ffcca64284cb21da4446f0b98f6': 'FLASV882709.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Listeriaceae,g:Listeria,s:MFD_s_286000;', '2889bb7d750a6398a62afb8bb634b591': 'FLASV891861.1383;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Enterococcaceae,g:Enterococcus,s:MFD_s_891861;', '5fa838c8d0afe988f17310370fc645b0': 'FLASV882709.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Listeriaceae,g:Listeria,s:MF

In [8]:
# Calculate mapping percentage
total_reads = alignment_counter["mapped"] + alignment_counter["unmapped"]
mapping_percentage = (alignment_counter["mapped"] / total_reads) * 100 if total_reads > 0 else 0
average_mapq = total_mapq / alignment_counter["mapped"] if alignment_counter["mapped"] > 0 else 0

# Print the results
print(f"Total Reads: {total_reads}")
print(f"Mapped Reads: {alignment_counter['mapped']}")
print(f"Unmapped Reads: {alignment_counter['unmapped']}")
print(f"Mapping Percentage: {mapping_percentage:.2f}%")
print(f"Average MAPQ: {average_mapq:.2f}")

Total Reads: 129
Mapped Reads: 129
Unmapped Reads: 0
Mapping Percentage: 100.00%
Average MAPQ: 0.36

In [11]:
#prepare metadata into dataframe with column name: sample-id, total reads, mapped reads, unmapped reads, mapping percentage, average mapq
metadata = pl.DataFrame({
    'sample-id': ['V1V2'],
    'total reads': [total_reads],
    'mapped reads': [alignment_counter['mapped']],
    'unmapped reads': [alignment_counter['unmapped']],
    'mapping percentage': [mapping_percentage],
    'average mapq': [average_mapq]
})

In [12]:
print(metadata)

shape: (1, 6)
┌───────────┬─────────────┬──────────────┬────────────────┬────────────────────┬──────────────┐
│ sample-id ┆ total reads ┆ mapped reads ┆ unmapped reads ┆ mapping percentage ┆ average mapq │
│ ---       ┆ ---         ┆ ---          ┆ ---            ┆ ---                ┆ ---          │
│ str       ┆ i64         ┆ i64          ┆ i64            ┆ f64                ┆ f64          │
╞═══════════╪═════════════╪══════════════╪════════════════╪════════════════════╪══════════════╡
│ V1V2      ┆ 129         ┆ 129          ┆ 0              ┆ 100.0              ┆ 0.356589     │
└───────────┴─────────────┴──────────────┴────────────────┴────────────────────┴──────────────┘

In [42]:
# Prepare metadata dictionary
metadata = {
    "Total Reads": total_reads,
    "Mapped Reads": alignment_counter["mapped"],
    "Unmapped Reads": alignment_counter["unmapped"],
    "Mapping Percentage": f"{mapping_percentage:.2f}%",
    "Average Mapping Quality": f"{average_mapq:.2f}"
}

In [50]:
filename=(f"/home/n11702427/m/users/r_nurdiansyah/wagtail/testing/3_mappy/meta/{basename}_metadata.txt")
with open(filename, 'w') as f:
    for key, value in metadata.items():
        f.write(f"{key}: {value}\n")
    print(f"Metadata successfully saved to {filename}")

Metadata successfully saved to /home/n11702427/m/users/r_nurdiansyah/wagtail/testing/3_mappy/meta/ERR4994172_metadata.txt

In [44]:
print(alignment_counter["mapped"])

11136

In [13]:
print(ctg_counts)

Counter({'FLASV883688.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Escherichia-Shigella,s:MFD_s_383;': 5, 'FLASV871300.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_24189;': 4, 'FLASV1017960.1381;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Enterococcaceae,g:Enterococcus,s:MFD_s_1017960;': 4, 'FLASV916992.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;': 4, 'FLASV884662.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Listeriaceae,g:Listeria,s:MFD_s_286000;': 4, 'FLASV414129.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;': 4, 'FLASV873342.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Escherichia-Shigella,s:MFD_s_1065;': 4, 'FLASV825639.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:MFD_s_825639;': 4, 'FLASV876361.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;': 4, 'FLASV891861.1383;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Enterococcaceae,g:Enterococcus,s:MFD_s_891861;': 4, 'FLASV832231.1372;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Staphylococcales,f:Staphylococcaceae,g:Staphylococcus,s:MFD_s_126847;': 3, 'FLASV662431.1374;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Pseudomonadales,f:Hahellaceae,g:Hahella,s:MFD_s_26319;': 3, 'FLASV876198.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Escherichia-Shigella,s:MFD_s_383;': 3, 'FLASV870482.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_24189;': 3, 'FLASV531209.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;': 3, 'FLASV336434.1381;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Enterococcaceae,g:Enterococcus,s:Enterococcus_faecalis;': 3, 'FLASV858257.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_24189;': 3, 'FLASV1008642.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Salmonella,s:MFD_s_69746;': 2, 'FLASV518250.1366;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Pseudomonadales,f:Moraxellaceae,g:Agitococcus_lubricus_group,s:MFD_s_2007;': 2, 'FLASV845393.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Listeriaceae,g:Listeria,s:MFD_s_286000;': 2, 'FLASV886356.1357;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Pseudomonadales,f:Pseudomonadaceae,g:Pseudomonas,s:Pseudomonas_aeruginosa;': 2, 'FLASV784595.1345;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Morganellaceae,g:Arsenophonus,s:MFD_s_784595;': 2, 'FLASV877831.1465;tax=d:Bacteria,p:Firmicutes,c:Clostridia,o:Clostridiales,f:Clostridiaceae,g:Clostridium_sensu_stricto_18,s:MFD_s_136;': 2, 'FLASV934985.1369;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_24189;': 2, 'FLASV934795.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_787515;': 2, 'FLASV981243.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Escherichia-Shigella,s:MFD_s_383;': 2, 'FLASV813265.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Listeriaceae,g:Listeria,s:MFD_s_286000;': 2, 'FLASV882709.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Listeriaceae,g:Listeria,s:MFD_s_286000;': 2, 'FLASV817681.1349;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Pseudomonadales,f:Pseudohongiellaceae,g:Pseudohongiella,s:MFD_s_817681;': 1, 'FLASV964003.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Escherichia-Shigella,s:MFD_s_889512;': 1, 'FLASV148929.1366;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Pseudomonadales,f:Moraxellaceae,g:Agitococcus_lubricus_group,s:MFD_s_2007;': 1, 'FLASV901271.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Listeriaceae,g:Listeria,s:MFD_s_286000;': 1, 'FLASV966006.1359;tax=d:Bacteria,p:Bacteroidota,c:Bacteroidia,o:Bacteroidales,f:Bacteroidaceae,g:Bacteroides,s:MFD_s_966006;': 1, 'FLASV986879.1380;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Enterococcaceae,g:Enterococcus,s:Enterococcus_faecalis;': 1, 'FLASV871303.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;': 1, 'FLASV941033.1359;tax=d:Bacteria,p:Bacteroidota,c:Bacteroidia,o:Bacteroidales,f:Bacteroidaceae,g:Bacteroides,s:MFD_s_941033;': 1, 'FLASV543385.1344;tax=d:Bacteria,p:Firmicutes,c:Clostridia,o:Christensenellales,f:Christensenellaceae,g:Christensenellaceae_R-7_group,s:MFD_s_3976;': 1, 'FLASV851631.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;': 1, 'FLASV759664.1354;tax=d:Bacteria,p:Firmicutes,c:Clostridia,o:Lachnospirales,f:Lachnospiraceae,g:Anaerostipes,s:Anaerostipes_hadrus;': 1, 'FLASV1001192.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Salmonella,s:MFD_s_69746;': 1, 'FLASV916969.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;': 1, 'FLASV975314.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Escherichia-Shigella,s:MFD_s_383;': 1, 'FLASV974262.1372;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Staphylococcales,f:Staphylococcaceae,g:Staphylococcus,s:MFD_s_126847;': 1, 'FLASV948923.1360;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Escherichia-Shigella,s:MFD_s_948923;': 1, 'FLASV979322.1399;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:MFD_s_979322;': 1, 'FLASV998171.1356;tax=d:Bacteria,p:Firmicutes,c:Clostridia,o:Lachnospirales,f:Lachnospiraceae,g:Agathobacter,s:MFD_s_998171;': 1, 'FLASV1030103.1353;tax=d:Bacteria,p:Firmicutes,c:Clostridia,o:Oscillospirales,f:Oscillospiraceae,g:UCG-005,s:MFD_s_1030103;': 1, 'FLASV982467.1357;tax=d:Bacteria,p:Firmicutes,c:Clostridia,o:Oscillospirales,f:Ruminococcaceae,g:Subdoligranulum,s:MFD_s_982467;': 1, 'FLASV819600.1381;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Enterococcaceae,g:Enterococcus,s:Enterococcus_faecalis;': 1, 'FLASV819669.1397;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:MFD_s_819669;': 1, 'FLASV889158.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Listeriaceae,g:Listeria,s:MFD_s_286000;': 1, 'FLASV126318.1354;tax=d:Bacteria,p:Firmicutes,c:Clostridia,o:Lachnospirales,f:Lachnospiraceae,g:Anaerostipes,s:Anaerostipes_hadrus;': 1, 'FLASV910107.1357;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Pseudomonadales,f:Pseudomonadaceae,g:Pseudomonas,s:Pseudomonas_aeruginosa;': 1, 'FLASV30172.1359;tax=d:Bacteria,p:Bacteroidota,c:Bacteroidia,o:Bacteroidales,f:Bacteroidaceae,g:Bacteroides,s:Bacteroides_xylanisolvens;': 1, 'FLASV821800.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_24189;': 1, 'FLASV970184.1352;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Erysipelotrichales,f:Erysipelatoclostridiaceae,g:Erysipelatoclostridium,s:MFD_s_970184;': 1, 'FLASV1011158.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Pseudomonadales,f:Pseudomonadaceae,g:Pseudomonas,s:MFD_s_1011158;': 1, 'FLASV893164.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_787515;': 1, 'FLASV122072.1353;tax=d:Bacteria,p:Firmicutes,c:Clostridia,o:Lachnospirales,f:Lachnospiraceae,g:Fusicatenibacter,s:Fusicatenibacter_saccharivorans;': 1, 'FLASV970677.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Listeriaceae,g:Listeria,s:MFD_s_286000;': 1, 'FLASV1002622.1372;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Staphylococcales,f:Staphylococcaceae,g:Staphylococcus,s:MFD_s_126847;': 1, 'FLASV780103.1363;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Salmonella,s:MFD_s_69746;': 1, 'FLASV786295.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Listeriaceae,g:Listeria,s:MFD_s_286000;': 1, 'FLASV1017348.1371;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Staphylococcales,f:Staphylococcaceae,g:Staphylococcus,s:MFD_s_126847;': 1, 'FLASV821309.1378;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_24189;': 1, 'FLASV994194.1372;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Staphylococcales,f:Staphylococcaceae,g:Staphylococcus,s:MFD_s_126847;': 1, 'FLASV876045.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Listeriaceae,g:Listeria,s:MFD_s_286000;': 1, 'FLASV880811.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Listeriaceae,g:Listeria,s:MFD_s_286000;': 1, 'FLASV859583.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_24189;': 1, 'FLASV903375.1372;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Staphylococcales,f:Staphylococcaceae,g:Staphylococcus,s:MFD_s_903375;': 1, 'FLASV1022410.1343;tax=d:Bacteria,p:Proteobacteria,c:Gammaproteobacteria,o:Enterobacterales,f:Enterobacteriaceae,g:Escherichia-Shigella,s:MFD_s_1022410;': 1, 'FLASV909873.1370;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Bacillales,f:Bacillaceae,g:Bacillus,s:MFD_s_787515;': 1, 'FLASV832298.1396;tax=d:Bacteria,p:Firmicutes,c:Bacilli,o:Lactobacillales,f:Lactobacillaceae,g:Limosilactobacillus,s:Lactobacillus_fermentum;': 1})

In [46]:
#get the base name of the input file
basename = os.path.basename(input).split('.')[0]
#remove the extension of the file
#basename = os.path.splitext(basename).split('.')[0]
print(basename)

ERR4994172

In [32]:
# Change the result per i into dataframe -> to match the table result
df = pl.from_dict(result_per_i)
df1 = df.transpose(include_header=True)
#result_per_i.columns = ['sample-id', 'ctg']
df1.columns = ['read', 'contig']
print(df1)

shape: (129, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ read                            ┆ contig                          │
│ ---                             ┆ ---                             │
│ str                             ┆ str                             │
╞═════════════════════════════════╪═════════════════════════════════╡
│ 1c952ffa899157451e1a0803a6e7d1… ┆ FLASV871300.1370;tax=d:Bacteri… │
│ 961fd2d00cf9d8631a7bf2e1e95467… ┆ FLASV1017960.1381;tax=d:Bacter… │
│ e2c0a94741782377cd3808323213ed… ┆ FLASV832231.1372;tax=d:Bacteri… │
│ 9508d1e293eb48991dbcbed8ac8cf5… ┆ FLASV871300.1370;tax=d:Bacteri… │
│ d4c2eddd7f6efef8a159f05deecf72… ┆ FLASV1017960.1381;tax=d:Bacter… │
│ …                               ┆ …                               │
│ faa404f26355ade0452744f952b680… ┆ FLASV903375.1372;tax=d:Bacteri… │
│ 433fb165118a2fa968618a0b7d914a… ┆ FLASV1022410.1343;tax=d:Bacter… │
│ aa77e018552a2cc9f2e708c55c974a… ┆ FLASV981243.1363;tax=d:Bacteri… │
│ 3966eca3da3f39e0d9905150e0fa5f… ┆ FLASV909873.1370;tax=d:Bacteri… │
│ 1f9e3d4552fec145e4e1a720890722… ┆ FLASV832298.1396;tax=d:Bacteri… │
└─────────────────────────────────┴─────────────────────────────────┘

In [23]:
df1.write_csv(f"/home/n11702427/m/users/r_nurdiansyah/wagtail/testing/3_mappy/align/V1V2_alignment.tsv", separator='\t')

In [26]:
test= pl.read_csv("/home/n11702427/m/users/r_nurdiansyah/wagtail/testing/3_mappy/align/V1V2_alignment.tsv", separator='\t', has_header=False)
test[:4]

shape: (4, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ column_1                        ┆ column_2                        │
│ ---                             ┆ ---                             │
│ str                             ┆ str                             │
╞═════════════════════════════════╪═════════════════════════════════╡
│ read                            ┆ contig                          │
│ 1c952ffa899157451e1a0803a6e7d1… ┆ FLASV871300.1370;tax=d:Bacteri… │
│ 961fd2d00cf9d8631a7bf2e1e95467… ┆ FLASV1017960.1381;tax=d:Bacter… │
│ e2c0a94741782377cd3808323213ed… ┆ FLASV832231.1372;tax=d:Bacteri… │
└─────────────────────────────────┴─────────────────────────────────┘

In [47]:
#record the ctg_counts dictionary to a tsv file using polars
df1 = pl.from_dict(ctg_counts)
df1 = df1.transpose(include_header=True)
#add sample column on the first column and fill the value with user's input (sample name)
df1.columns = ['contig', 'count']
df1 = df1.with_columns(pl.Series("sample", [basename]*len(df1)))
#reorder the column to match the biobox script input while delete the unnecessary columns
df1 = df1[["sample", "contig", "count"]]
#sort based on count
df2 = df1.sort("count", descending=True)
df2[:4]

shape: (4, 3)
┌────────────┬───────────────────────────────────┬───────┐
│ sample     ┆ contig                            ┆ count │
│ ---        ┆ ---                               ┆ ---   │
│ str        ┆ str                               ┆ i64   │
╞════════════╪═══════════════════════════════════╪═══════╡
│ ERR4994172 ┆ FLASV957672.1365;tax=d:Bacteria,… ┆ 2875  │
│ ERR4994172 ┆ FLASV60.1391;tax=d:Bacteria,p:Fi… ┆ 2148  │
│ ERR4994172 ┆ FLASV89.1392;tax=d:Bacteria,p:Fi… ┆ 871   │
│ ERR4994172 ┆ FLASV927273.1364;tax=d:Bacteria,… ┆ 592   │
└────────────┴───────────────────────────────────┴───────┘

In [49]:
df2.write_csv(f"/home/n11702427/m/users/r_nurdiansyah/wagtail/testing/3_mappy/align/{basename}_alignment.tsv", separator='\t')

In [18]:
for i in input_files:
    result_per_i = {}
    #Loop through single-end reads
    for name, seq, qual in mp.fastx_read(i):
        barcode = os.path.basename(i).split('.')[0]
        names = "{}_barcode+{}".format(barcode, name)
        #Perform single-end alignment
        for hits in ref.map(seq, cs=True, MD=True):
            if hits.is_primary:
                result_per_i[names] = (hits.ctg)
    #count the number of contigs using Counter
    ctg_counts = Counter(result_per_i.values())
print(ctg_counts)

Counter()

In [6]:
for i in input:
    result_per_i = {}
    #Loop through single-end reads
    for name, seq, qual in mp.fastx_read(i):
        barcode = os.path.basename(i).split('.')[0]
        names = "{}_barcode+{}".format(barcode, name)
        #Perform single-end alignment
        for hits in ref.map(seq, cs=True, MD=True):
            if hits.is_primary:
                result_per_i[names] = (hits.ctg)
    #count the number of contigs using Counter
    ctg_counts = Counter(result_per_i.values())
print(ctg_counts)

Counter()

In [9]:
# Check if input is a file or a directory and list all files in the directory
input_files=[]
printout=[]
#d = AmpliconDataset()
if isinstance (input, str):
    input = [input] #convert to list if input is a string
    
input_file = sorted(input_files)
file_names = [os.path.basename(f) for f in input_files]

d = AmpliconDataset()
datasets = []
for file in file_names:
    base = file.split('.')[0]
    d.basename = base
    datasets.append(d)

for input in input_file:
    d.input_file = input
    datasets.append(d)

print(d.input_file)
print(d.basename)

None
None

In [63]:
#making directory, no need to run this
for d in datasets:
    file = d.basename
    # Extract parent directory name (first 3 digits after "ERR")
    if len(file) < 6:
        logging.error(f"Filename {file} is too short")
        sys.exit(1)
    parent_dir = file[:6]
    
    # Extract the last digit to determine the subdirectory ("000" to "009")
    sub_dir_num = int(file[-3:]) % 1000
    
    # Create the full path for the accession directory
    new_dir = os.path.join(output, f"{parent_dir}", f"{sub_dir_num}", file)
    d.output_directory = new_dir
          
    #Create new directory if not exist
    if not os.path.exists(new_dir):
        os.makedirs(new_dir, exist_ok=True)
        logging.info(f"Created directory: {new_dir}")
    else:
        logging.info(f"Directory already exists: {new_dir}")

In [12]:
# Create empty lists to store alignment data and metadata counts
alignments = []
has_primary_flags = {}

In [20]:
for i in input:
    result_per_i = {}
    #Loop through single-end reads
    for name, seq, qual in mp.fastx_read(i):
        barcode = os.path.basename(i).split('.')[0]
        names = "{}_barcode+{}".format(barcode, name)
        #Perform single-end alignment
        for hits in ref.map(seq, cs=True, MD=True):
            if hits.is_primary:
                result_per_i[names] = (hits.ctg)
    #count the number of contigs using Counter
    ctg_counts = Counter(result_per_i.values())
print(ctg_counts)

Counter()

In [18]:
# Process each input sequence in the input file (assuming FASTA/FASTQ format)
for i in input:
    result_per_i = {}
    for name, seq, qual in mp.fastx_read(i):
        alignment_counts['total'] += 1
        #has_primary = False  # To track duplicates

        for hits in ref.map(seq, cs=True, MD=True):
            if hits.is_primary:
                result_per_i[names] = (hits.ctg)
        #count the number of contigs using Counter
    ctg_counts = Counter(result_per_i.values())
print(ctg_counts)
        # # Perform alignment and store results
        # for hit in aligner.map(seq):
        #     # Store alignment result in list
        #     alignments.append([name, hit.ctg])

        #     if hit.is_primary and not has_primary:
        #         alignment_counts['primary'] += 1
        #         has_primary = True
        #     elif hit.is_secondary:
        #         alignment_counts['secondary'] += 1
        #     if hit.is_supplementary:
        #         alignment_counts['supplementary'] += 1
        #     if has_primary and hit.is_primary:  # Mark duplicates
        #         alignment_counts['duplicates'] += 1

print(alignments)
    # Convert alignment list to Polars DataFrame and save as TSV
    # alignment_df = pl.DataFrame(alignments, schema=["read_name", "ctg"])
    # alignment_df.write_csv(alignment_output, separator="\t", has_header=True)

Counter()
[]

In [53]:
for da in datasets:
    i = da.input_file
    d = da.output_directory

    print("Running analysis for {}".format(i))
    result_per_i = {}
    ctg_counts = Counter()
    #Loop through single-end reads
    for name, seq, qual in mp.fastx_read(i):
        barcode = os.path.basename(i).split('.')[0]
        names = "{}_barcode+{}".format(barcode, name)
        #Perform single-end alignment
        for hits in ref.map(seq, cs=True, MD=True):
            if hits.is_primary:
                result_per_i[names] = (hits.ctg)
        #count the number of contigs using Counter
        ctg_counts.update(result_per_i.values())
        print(ctg.counts)

Running analysis for V3V4005.fastq.gz
Running analysis for V1V2002.fastq.gz
Running analysis for V1V2001.fastq.gz
Running analysis for V4V6007.fastq.gz
Running analysis for V4V6008.fastq.gz
Running analysis for V1V3004.fastq.gz
Running analysis for V3V4006.fastq.gz
Running analysis for V1V3003.fastq.gz

In [36]:
help(mp)

Help on module mappy:

NAME
    mappy

CLASSES
    builtins.object
        Aligner
        Alignment
        ThreadBuffer

    class Aligner(builtins.object)
     |  Methods defined here:
     |
     |  __bool__(self, /)
     |      True if self else False
     |
     |  __reduce__ = __reduce_cython__(...)
     |
     |  __setstate__ = __setstate_cython__(...)
     |
     |  map(self, seq, seq2=None, buf=None, cs=False, MD=False, max_frag_len=None, extra_flags=None)
     |
     |  seq(self, name, start=0, end=2147483647)
     |
     |  ----------------------------------------------------------------------
     |  Static methods defined here:
     |
     |  __new__(*args, **kwargs)
     |      Create and return a new object.  See help(type) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  k
     |
     |  n_seq
     |
     |  seq_names
     |
     |  w

    class Alignment(builtins.object)
     |  Methods defined here:
     |
     |  __reduce__ = __reduce_cython__(...)
     |
     |  __setstate__ = __setstate_cython__(...)
     |
     |  __str__(self, /)
     |      Return str(self).
     |
     |  ----------------------------------------------------------------------
     |  Static methods defined here:
     |
     |  __new__(*args, **kwargs)
     |      Create and return a new object.  See help(type) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  MD
     |
     |  NM
     |
     |  blen
     |
     |  cigar
     |
     |  cigar_str
     |
     |  cs
     |
     |  ctg
     |
     |  ctg_len
     |
     |  is_primary
     |
     |  mapq
     |
     |  mlen
     |
     |  q_en
     |
     |  q_st
     |
     |  r_en
     |
     |  r_st
     |
     |  read_num
     |
     |  strand
     |
     |  trans_strand

    class ThreadBuffer(builtins.object)
     |  Methods defined here:
     |
     |  __reduce__ = __reduce_cython__(...)
     |
     |  __setstate__ = __setstate_cython__(...)
     |
     |  ----------------------------------------------------------------------
     |  Static methods defined here:
     |
     |  __new__(*args, **kwargs)
     |      Create and return a new object.  See help(type) for accurate signature.

FUNCTIONS
    __reduce_cython__(self)

    __setstate_cython__(self, __pyx_state)

    fastx_read(fn, read_comment=False)

    revcomp(seq)

    verbose(v=None)

DATA
    __test__ = {}

VERSION
    2.28

FILE
    /mnt/hpccs01/work/microbiome/users/r_nurdiansyah/e/minimap-update/lib/python3.12/site-packages/mappy.cpython-312-x86_64-linux-gnu.so